name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u varokas --password-stdin
    - name: Build Image
      run: docker build . -t varokas/spark:${GITHUB_SHA::8}
    - name: Push Image
      run: docker push varokas/spark:${GITHUB_SHA::8}
    - name: Tag new Image as Latest
      run: docker tag varokas/spark:${GITHUB_SHA::8} varokas/spark:latest
    - name: Push Latest
      run: docker push varokas/spark:latest
